// bangkok/28-create-polka-dapp/src/templates/frontend/vara-next-ts_d/src/components/connect-wallet-components/ConnectAccountButton.tsx
import React, { useState } from "react";
import useConnectedWalletStore from "../../zustand/useConnectWalletStore";
import type { Account } from "@polkadot-onboard/core";
import Image from "next/image";

const shorten = (str: string | undefined) => {
  if (!str) return str;
  const size = 10;
  let result = str;
  if (str && str.length > 2 * size) {
    const start = str.slice(0, size);
    const end = str.slice(-size);
    result = `${start}...${end}`;
  }
  return result;
};

export default function ConnectAccountButton() {
  const { accounts, connectAccount, connectedWallet } =
    useConnectedWalletStore();

  const [showAccounts, setShowAccounts] = useState(false);

  function AccountItem({ account }: { account: Account }) {
    return (
      <div className="account-item">
        <div className="account-name">{shorten(account?.name)}</div>
        <div>{shorten(account?.address)}</div>
        <div>
          <button
            type="button"
            onClick={() => {
              connectAccount(account);
            }}
          >
            Connect Account
          </button>
        </div>
      </div>
    );
  }

  if (accounts.length === 0) {
    return <div>You have No Account</div>;
  }

  return (
    <div>
      <div>
        <div className="show-accounts">
          {connectedWallet?.metadata?.iconUrl && (
            <Image
              width={25}
              height={25}
              src={connectedWallet.metadata.iconUrl}
              alt="wallet icon"
            />
          )}

          <button
            type="button"
            onClick={() => {
              setShowAccounts(!showAccounts);
            }}
          >
            {showAccounts ? "Hide Accounts" : "Show Accounts"}
          </button>
        </div>

        {showAccounts && (
          <dialog open>
            <div className="accounts-list">
              {accounts.map((account) => (
                <AccountItem key={account.address} account={account} />
              ))}
            </div>
          </dialog>
        )}
      </div>
    </div>
  );
}

// bangkok/28-create-polka-dapp/src/templates/frontend/svelte-ts_d/src/lib/components/connect-wallet-components/ConnectAccountButton.svelte
<script lang='ts'>
import useConnectedWalletStore from "../../store/useConnectWalletStore";
import AccountItem from "./AccountItem.svelte";

let showAccounts = false;

const toggleShowAccounts = () => {
    showAccounts = !showAccounts;
}

</script>

    <div>
        {#if $useConnectedWalletStore.accounts.length === 0}
           <div>You have No Account</div>;
          {:else}
    <div>
        <div class="show-accounts">
            {#if $useConnectedWalletStore.connectedWallet?.metadata?.iconUrl}
                            <img
              width={25}
              height={25}
              src={$useConnectedWalletStore.connectedWallet.metadata.iconUrl}
              alt="wallet icon"
            />
            {/if}

          <button
            type="button"
            on:click={() => {
              toggleShowAccounts();
            }}
          >
            {showAccounts ? "Hide Accounts" : "Show Accounts"}
          </button>
        </div>

        {#if showAccounts}
          <dialog open>
            <div class="accounts-list">
            {#each $useConnectedWalletStore.accounts as account (account.address)}
                <AccountItem account={account} />
            {/each}
            </div>
          </dialog>            
        {/if}
    </div>
        {/if}
    </div>

<style>
  /* Add your styles here */
</style>
