// bangkok/28-create-polka-dapp/src/templates/frontend/vara-next-ts_d/src/components/connect-wallet-components/Wallet.tsx
import React from "react";
import { memo } from "react";
import type { BaseWallet } from "@polkadot-onboard/core";
import useConnectedWalletStore from "../../zustand/useConnectWalletStore";
import Image from "next/image";

const Wallet = ({ wallet }: { wallet: BaseWallet }) => {
  const { connectWallet } = useConnectedWalletStore();

  const connectWalletHandler = async () => {
    connectWallet(wallet);
  };

  return (
    <div className="wallet-option">
      {wallet?.metadata?.iconUrl && (
        <Image
          width={25}
          height={25}
          src={wallet.metadata.iconUrl}
          alt="wallet icon"
        />
      )}
      <div>{`${wallet.metadata.title}`}</div>

      <button type="button" onClick={connectWalletHandler}>
        Connect Wallet
      </button>
    </div>
  );
};

const MemoWallet = memo(Wallet);

export default MemoWallet;

// bangkok/28-create-polka-dapp/src/templates/frontend/svelte-ts_d/src/lib/components/connect-wallet-components/Wallet.svelte
<script lang='ts'>
import { createEventDispatcher } from 'svelte';
import type { BaseWallet } from "@polkadot-onboard/core";
import useConnectedWalletStore from "../../store/useConnectWalletStore";

    export let wallet: BaseWallet; // Receive wallet as a prop


const connectWalletHandler = async () => {
   $useConnectedWalletStore.connectWallet(wallet);
  };

</script>

<div>
    <div class="wallet-option">
        {#if wallet?.metadata?.iconUrl}
        <img
          width={25}
          height={25}
          src={wallet.metadata.iconUrl}
          alt="wallet icon"
        />
        {/if}

      <div>{`${wallet.metadata.title}`}</div>

      <button type="button" on:click={connectWalletHandler}>
        Connect Wallet
      </button>
    </div>
</div>

<style>
  /* Add your styles here */
</style>
